name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (backend)
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies (frontend)
        run: |
          cd frontend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend tests
        run: |
          cd backend
          if [ -d "tests" ]; then pytest; else echo "No tests directory"; fi
      - name: Run frontend tests
        run: |
          cd frontend
          if [ -d "tests" ]; then pytest; else echo "No tests directory"; fi 